### ISSUE TITLE
List all files in a bucket with prefix

### ISSUE THREAD

**Issue by PaulVelthuis93** [dask/gcsfs#122]
I am trying to list all objects in a bucket with a certain prefix, however I get only the directories back one layer deeper. How is it possible to list all the files in the prefix

import gcsfs
fs = gcsfs.GCSFileSystem(project='project-id')

file_list= fs.ls('bucket/prefix/')

result:
file_list=[ bucket/prefix/anotherprefix,  bucket/prefix/anotherprefix]

I would expected  the following result result:
file_list[bucket/prefix/anotherprefix/file.txt, bucket/prefix/anotherprefix/file.txt]

How can I achieve this result?

**Comment by martindurant** [comment]
The method you want is `.walk()`.

Two notes:
- walk works by recursively listing files inside directories. It is possible to list all files below a prefix directly in the GCS API, but there is no method to call it, so you are not getting full efficiency. This has been this way for a long time, in order to guard against buckets with very large numbers of files
- in the ongoing work to move towards compliance with fsspec ( #116 ), the `walk()` will change to behave like the builtins `os` version, yielding an iterator, and the current functionality will be renamed `find()`. That new method can maybe call the more direct, efficient API.

**Comment by anuragbisht-turing** [comment]
import fsspec
fs = fsspec.filesystem("gcs") 
#gcs url can contain the full path till directory 
files = fs.ls(gcs_url)
