### ISSUE TITLE
Warning when import gcsfs

### ISSUE THREAD

**Issue by qibin-google** [dask/gcsfs#127]
It says 'No module named dask.bytes.core'. We are using gcsfs 0.2.0

**Comment by martindurant** [comment]
gcsfs is an optional backend for Dask, so that it can read from GCS within several processes or across a cluster. gcsfs tries to register itself with the Dask file-system dispatcher at import time to enable this. In your case, you seem no to have Dask, so that registration process fails, and you see the message. You can safely ignore it - but might be interested to find out about what Dask is how it can perhaps be useful to you: http://dask.pydata.org/en/latest

**Comment by qibin-google** [comment]
Hi Martin, 

Thanks for the quick response. yeah, dask seems to be a very useful library. We will consider it when we need it.

Do you have plan to hide the warning? I think gcsfs should be able to work by itself. We will use gcsfs in our product. It might be better to hide the warning message.

Best,

Qibin

**Comment by martindurant** [comment]
You are probably right. Few people see it, because Dask is included in the Anaconda download installer.

At the moment, the code uses `print` if the import fails, so it is hard to hide. It could instead be a Warning or logger output, so the user has control. Would you be interested in making a PR to do that? The relevant line is [here](https://github.com/dask/gcsfs/blob/master/gcsfs/dask_link.py#L124).

**Comment by qibin-google** [comment]
Sure. I am interested in that since it will help our team.

**Comment by yiga2** [comment]
@martindurant  could you consider skipping it especially if dask library is not installed, or switching off the import attempts through a parameter (or module variable) ?

Our primary use of `gcsfs` is in serverless functions (lambda, google cloud functions) so dask will not apply.

**Comment by qibin-google** [comment]
Hi Martin,

Don't worry. We wouldn't skip it normally. I will send you a PR, which skips registration if dask is not installed. Is that OK?

Also do you require a CLA? Thanks.

Best,

Qibin

**Comment by martindurant** [comment]
Yes, certainly provide a PR.
No CLA here, this is totally OSS.

**Comment by qibin-google** [comment]
Hi Martin,

I just sent a PR for you to review for this issue.

Thanks.

Qibin

**Comment by dakl** [comment]
Thanks for a great lib! How about a patch release to 0.2.1 now that #129 is merged?

**Comment by martindurant** [comment]
I am waiting on #132 , but yes, soon.
