### ISSUE TITLE
Speed gcsfs vs google.storage

### ISSUE THREAD

**Issue by NegatioN** [dask/gcsfs#223]
Are you considering using the official api-clients of Google as a backend at some point? https://googleapis.github.io/google-resumable-media-python/latest/google.resumable_media.requests.html#chunked-downloads

For a file of ~1GB from a region-local bucket, I see a speed increase from ~22s with gcsfs to around ~12s by downloading with the newest google.storage API.

I really love the abstractions in this library a lot more than the official one though, so I'm curious as to the plans going forward.

I might start to toy around with replacing some of these things myself, but I'm not sure I can promise a full conversion patch

**Comment by NegatioN** [comment]
Please ignore this. This does not seem to be the case.

**Comment by TomAugspurger** [comment]
Thanks. For the record, I asked @martindurant about this a couple weeks ago and he mentioned that the `google.storage` APIs were very rough a year or two ago when he last looked. I don't think we're against using them in principle, but last time it was evaluated using the REST API was the better option.

**Comment by martindurant** [comment]
Also it should be noted, that raw up/download speeds may be faster in some sync version of the library, if they use threads and/or async internally. gcsfs single-threaded, but with Dask in mind for parallelism.

**Comment by bnaul** [comment]
One thing I have noticed is that listing performance can much worse than `gsutil` but I'm not sure what they're doing internally:
```
(.venv) ➜  model git:(master) ✗ time (noglob gsutil ls gs://model-.../dt=*/.../*.pgp | wc)
    124     124   17608
1.53s user 0.31s system 8% cpu 21.512 total

path = ... # ^ same path, 124 files matched
%time fs.glob(path)
CPU times: user 23.8 s, sys: 2.21 s, total: 26.1 s
Wall time: 9min 5s
```
I assume `gsutil` is somehow pruning more intelligently w/ prefixes, any ideas on how to accomplish the same thing in `gcsfs`?

**Comment by martindurant** [comment]
There are two things that can be done, which are mutually exclusive but each would help:
- instead of recursing, get one bulk listing all files below a prefix without using the separators to make subdirectories. That would mean you cannot iterate over directories like walk() should, unless you reconstruct all the names into prefix directories in code
- applying the glob pattern during recursion, so that you don't list directories in which no files could possibly match

I would guess that gsutil does the first of these two. Could probably test by looking at the total download payload size as the glob of dir structure changes.
