### ISSUE TITLE
FeatReq: batch batch-deleting

### ISSUE THREAD

**Issue by yiga2** [dask/gcsfs#252]
`GCSFileSystem.rm()` supports batch-deleting, which is great  and not supported in G client lib as of this writing. However it does make only one http call regardless of the numbers of keys to delete. 

I guess to avoid timing out, G recommends splitting requests in batch of 100: https://cloud.google.com/storage/docs/json_api/v1/how-tos/batch 

Besides the recommended limit, the http request could end up being to large to handle by the server e.g. 10K bundled API calls.

Feature request in `rm()` to split in batches of 100, ideally using multithreading e.g. aiohttp. to maximize parallelism.

**Comment by yiga2** [comment]
If agreeable, we could start using `MultipartEncoder()` in `requests_toolbelt` library to avoid building the multipart ourselves - here and elsewhere.

**Comment by martindurant** [comment]
Certainly a good idea to avoid the GCS limits - I have not violated them myself so far.
About concurrent execution, though, that's a bit more fraught, because we don't know, within the library code, what IOloop or thread pool the caller may have in place. As things stand, all the fsspec-based implementations are synchronous, but the suggestion for async has been made elsewhere (multi-threading you could do for yourself already). 


- for async: a lot of rewrite would need to be done with a new async IO backend, with some logic over what can or can't be done concurrently (e.g., can't upload a file chunk before the upload session has been created)
- for threads, the connection session will not necessarily be thread-safe

**Comment by martindurant** [comment]
done
