### ISSUE TITLE
Slow performance to read data 

### ISSUE THREAD

**Issue by MikeChenfu** [dask/gcsfs#262]
Hello team, I try reading data in gcs by `cudf.read_orc`. The performance is pretty slower than the `google.cloud` method. The `orc` data is about 500MB. `gcsfs` takes 1-2 mins to read, but the google.cloud only takes 8s to download and 3s to read by cudf. Appreciate it if anyone has suggestions about this problem.

gcsfs(1-2 mins):
```
import gcsfs
import cudf
from functools import partial
read_orc = partial(cudf.read_orc, use_index=False)
fs = gcsfs.GCSFileSystem(token = 'credential.json' )
tname = 'buckets/file.orc'
with fs.open(tname, 'rb') as f:
    text = read_orc(f, columns=None)
```

google.cloud(8s + 3s):
```
#8s
from google.cloud import storage
storage_client = storage.Client.from_service_account_json('credential.json')
bucket = storage_client.get_bucket('buckets')
blob = storage.blob.Blob('file.orc',bucket)
blob.download_to_filename('./f.orc')
#3s
text = read_orc(`f.orc`)
```

**Comment by martindurant** [comment]
Indeed, if you were to download the file with gcsfs first, you will find better performance (perhaps between the two times you posted). The reason is, that for a download, you read from the first byte to the last in a streaming manner. When you read the file with ORC, however, your access pattern is very different: first to read the footer of the file for metadata, then to jump around in the file finding the various stripes chunks. The latter pattern might be very inefficient, requiring multiple connections and hard to implement a buffering scheme that can ameliorate it. However, having real random access might be essential for the case that you don't have enough local storage to download the file or only want to read a smaller piece of a larger file (e.g., if you are distributing the work on a cluster).

**Comment by MikeChenfu** [comment]
Thanks @martindurant  for the reply. 
I tried the download with `gcsfs`. It still takes 1-2 mins. 
```
fs.download( tname, './f1.orc')
```

**Comment by martindurant** [comment]
I would be interested to see a profile of this. It may be that the CLI is using parallelisation, while gcsfs is serial. You might do better by changing the blocksize parameter.

**Comment by martindurant** [comment]
Perhaps you can use `snakeviz` on the call and post the results?

**Comment by MikeChenfu** [comment]
@martindurant I have tried different blocksize, but still get the same performance and `gsutil` actually achieve better performance. I am gonna do more tests.

**Comment by martindurant** [comment]
I intend to work on async functionality for fsspec and its implementations, which should see a massive improvement in download/access speeds for many workloads. I expect snakeviz will show much of your time is spent in establishing connections.

**Comment by drubinstein** [comment]
I hope it's okay I revive this issue, but can make another if needed. Since this issue was created, Google added a [transfer_manager](https://cloud.google.com/python/docs/reference/storage/latest/google.cloud.storage.transfer_manager) api to its Google Cloud Storage Python SDK. I believe if you change the gcsfs implementation of `get` and `put` to use the correct `transfer_manager` function instead, then you can get some very good speedups (I personally experienced a 15x speed up of a 100+GB directory by using the `transfer_manager`.

**Comment by martindurant** [comment]
@drubinstein , do you think you can make a PR showing how this would be achieved, and maybe also show how you did your benchmarking (15x speedup sounds too good to be true!).

**Comment by drubinstein** [comment]
I'll try to put something together this week. It'll use google.cloud.storage which I hope you're okay with. There's a chance that adding multiprocessing (which what transfer_manager does under the hood) could show similar performance improvements.

I did my benchmarking by using `time.time()` around the function, e.g.

```python
start = time.time()
transfer_manager.download_many()
print(f"Downloaded in {time.time() - start}s")
```

 The 15x speed up was when a directory of files that was 100GB - 1TB in size.

**Comment by martindurant** [comment]
I was more interested in seeing what the gcsfs usage was :). Also, it sounds like the number of available cores, the network bandwidth and data locality are probably material.

> There's a chance that adding multiprocessing

Maybe something that dask could do for us, rather than having to manage processes (and all their threads and loops) ourselves.

**Comment by martindurant** [comment]
There are absolutely no objections to building plumbing to increase performance in gcsfs! Hopefully, it doesn't come at the cost of current usability or extra code complexity.
