### ISSUE TITLE
gcsfs==0.6.1|0.6.2 'walk()' method breaking dask dataframe

### ISSUE THREAD

**Issue by hermesribeiro** [dask/gcsfs#272]
**What happened**:
While walking the root of a `parquet` folder initially created by pyspark, the `fs.walk` method returns an empty string `''` in the files list. 

```shell
('path/to/parquet/folder',
 ['Year=2019', 'Year=2020'],
 ['', '_SUCCESS'])
```

This behavior is breaking `dask.dataframe.read_parquet('gs://...')` on multiple occasions (let me know if you want these errors), that's when I tracked the error down to `fs.walk`.

**What you expected to happen**:

The correct output should be

```shell
('path/to/parquet/folder',
 ['Year=2019', 'Year=2020'],
 [ '_SUCCESS'])
```

**Minimal Complete Verifiable Example**:

```python
import gcsfs
next(gcsfs.GCSFileSystem().walk('gs://path/to/parquet/folder/'))
```

**Anything else we need to know?**:

Reverting to `gcsfs==0.6.0`, seemed to solve this problem. As far as I tested, the problem happens with `0.6.1` and `0.6.2` versions.

**Environment**:

- Dask version: 2.21.0
- GCSFS version: 0.6.2
- Python version: 3.7.6
- Operating System: Ubuntu 18.04
- Install method (conda, pip, source): pip

**Comment by martindurant** [comment]
Can you check on gcsfs master, please?

**Comment by hermesribeiro** [comment]
`import gcsfs` gives the following error when installed from source.
```shell
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/hermes/.pyenv/versions/3.7.7/lib/python3.7/site-packages/gcsfs/__init__.py", line 5, in <module>
    from .core import GCSFileSystem
  File "/home/hermes/.pyenv/versions/3.7.7/lib/python3.7/site-packages/gcsfs/core.py", line 34, in <module>
    from fsspec.asyn import sync_wrapper, sync, AsyncFileSystem
ModuleNotFoundError: No module named 'fsspec.asyn'
```

**Comment by martindurant** [comment]
Yeah, you need fsspec master too, sorry

**Comment by hermesribeiro** [comment]
No problems.
Tested here, same return from `fs.walk(gs://...)` using master.

```shell
('path/to/parquet/folder',
 ['Year=2019', 'Year=2020'],
 ['', '_SUCCESS'])
```

**Comment by martindurant** [comment]
Do those paths show up with `fs.find('path/to/parquet/folder')` ?

**Comment by martindurant** [comment]
Another thought, can you tell (perhaps in the web console) whether there is a *key* with the name 'path/to/parquet/folder', as well as the path prefix?

**Comment by hermesribeiro** [comment]
These paths indeed show up with `fs.find`. I compared against `0.6.0` and the responses are:

Master:
```python
['path/to/parquet/folder/',
 'path/to/parquet/folder/Year=2019/',
 'path/to/parquet/folder/Year=2019/Month=10/',
 'path/to/parquet/folder/Year=2019/Month=10/Day=10/',
 'path/to/parquet/folder/Year=2019/Month=10/Day=10/part-00000-e68b8f31-bd2d-4215-a9c3-e183715a74e4.c000.snappy.parquet',
``` 

0.6.0:
```python
['path/to/parquet/folder/Year=2019/Month=10/Day=10/part-00000-e68b8f31-bd2d-4215-a9c3-e183715a74e4.c000.snappy.parquet',
 'path/to/parquet/folder/Year=2019/Month=10/Day=10/part-00001-e68b8f31-bd2d-4215-a9c3-e183715a74e4.c000.snappy.parquet',
 'path/to/parquet/folder/Year=2019/Month=10/Day=11/part-00000-c1933285-a2fe-42c8-864d-569a78a33af9.c000.snappy.parquet',
 'path/to/parquet/folder/Year=2019/Month=10/Day=11/part-00001-c1933285-a2fe-42c8-864d-569a78a33af9.c000.snappy.parquet',
```

**Comment by hermesribeiro** [comment]
> Another thought, can you tell (perhaps in the web console) whether there is a key with the name 'path/to/parquet/folder', as well as the path prefix?
Sorry, where should I look for that key?

**Comment by martindurant** [comment]
I thought it might show up in the console ( https://console.cloud.google.com/storage/browser )

Maybe you could do 
```
gcs.cat('path/to/parquet/folder/')
```
(try with or without the trailing "/", and perhaps with or without `gcs.invalidate_cache()` first)
If there is a key, you will get a bytes object back, perhaps of zero length.

**Comment by hermesribeiro** [comment]
Thanks. Console shows this:
![Screenshot from 2020-07-28 17-09-49](https://user-images.githubusercontent.com/14008626/88716471-811dcc00-d0f5-11ea-9baa-0a1764c3041a.png)

`gcs.cat` also breaks on master:

```shell
/usr/local/lib/python3.7/site-packages/gcsfs/core.py in validate_response(self, status, content, json, path, headers)
   1192 
   1193             if status == 404:
-> 1194                 raise FileNotFoundError
   1195             elif status == 403:
   1196                 raise IOError("Forbidden: %s\n%s" % (path, msg))

FileNotFoundError: 
```
While 0.6.0 returns:

```shell
b''
```

**Comment by martindurant** [comment]
Now I'm totally confused, that's the opposite of what I would have expected. Since at least one of the versions returns a real response, I think I can definitively say that the key *does* exist, which means that spark was doing the equivalent of mkdir during writing, and then using the convention of placing a key with the directory name and zero size (this is not defined in the GCS API).

So, to fix:
- we could remove [this line](https://github.com/intake/filesystem_spec/blob/master/fsspec/spec.py#L366) which explicitly checks for files with the same name as directories
- change gcsfs ls not to return the file itself, if a deeper nested listing is available (this may have implications of not being able to delete all keys in a directory tree)
- look carefully again on the use of trailing "/" to indicate that a path is supposed to be interpreted as a directory

Note that parquet files produces by arrow/fastparquet do *not* have these duplicate names, so I don't actually have a bucket in which I'm seeing this problem!

**Comment by hermesribeiro** [comment]
Mmm, maybe that's what spark is doing.

I guess removing the line above would certainly work if substituded for `pass` or something similar. The `elif` condition must remain, though, since the subsequent `else` clause would cause the same behavior.

I created a mock dataset using pyspark on GCS and made it public so you can test at will on `gs://hermes-misc/mock_append`.

**Comment by martindurant** [comment]
So yes, I can immediately see that there are keys with the same names as directories: they show up with `gcs.find`, and I can grab them not with, e.g.,
```
>>> gcs.cat('hermes-misc/mock_append/Year=2020/Month=2/Day=21%2F')
b""
```
(where I had to use the URL-encoded value for "/", to prevent it being stripped)

So now we know what the problem is... One could argue that `walk` was doing the right thing, although obviously this never happens in real filesystems, so the situation is undefined.

**Comment by martindurant** [comment]
OK, find should get all of the paths now. Please reopen if I am wrong.

**Comment by rjurney** [comment]
@martindurant @hermesribeiro I have this bug on the latest Dask and gcsfs from PyPi.

**Comment by martindurant** [comment]
@rjurney , please open a new issue with the specific case that you are seeing
