### ISSUE TITLE
Optimise find()

### ISSUE THREAD

**Issue by alimanfoo** [dask/gcsfs#273]
For zarr (v3) I'd like to locate all objects with a given prefix. This is useful, e.g., when you want to discover all nodes in a hierarchy, you can get this by listing all objects with the prefix "meta/". 

The fsspec find() method seems to be the right API for this. However, IIUC, this is currently implemented via walk(), which makes multiple calls to ls(), each of which calls _do_list_objects(), each of which makes a GCS API call to list the bucket with both prefix and delimiter arguments. 

Instead, could find() could be implemented more efficiently by making a single GCS list bucket request with the prefix argument only?

**Comment by alimanfoo** [comment]
Apologies I haven't done any benchmarking, and may have missed something in the code, but thought I'd ask the question to get a quick sanity check.

**Comment by martindurant** [comment]
You have a good point: this happened because walk() came first, and the default iterative implementation works for all filesystems. Actually we used to list all keys in a bucket originally, and construct the directories ourselves, but some buckets are far too big for that.

A similar conversation came up recently for s3fs.
It raises the following points:
- there may be an opportunity to list files using concurrent calls and slightly different prefixes under the root prefix; assuming the naming scheme is something reasonable (e.g., `prefixes = [. Otherwise, paginating 1000 keys per call means listing everything sequentially
- how would this interact with the existing directory cache, just ignore it or populate it? What if `find()` is called on a higher-level directory when we have some part of the listings already cached?
- should `ls` optionally use this mode, if the user asserts they will want to delve into nested directories?

Honestly, directory management is by far the thing I've spent the most time on with gcsfs/s3fs (another recent one: https://github.com/dask/gcsfs/issues/272 ), would like to see it done rigorously and not touched again!

(cc @mariusvniekerk )

**Comment by martindurant** [comment]
You could play with the following:
```diff
--- a/gcsfs/core.py
+++ b/gcsfs/core.py
@@ -608,7 +608,7 @@ class GCSFileSystem(AsyncFileSystem):
         self.dircache[path] = out
         return out

-    async def _do_list_objects(self, path, max_results=None):
+    async def _do_list_objects(self, path, max_results=None, delimiter="/"):
         """Object listing for the given {bucket}/{prefix}/ path."""
         bucket, prefix = self.split_path(path)
         prefix = None if not prefix else prefix.rstrip("/") + "/"
@@ -619,7 +619,7 @@ class GCSFileSystem(AsyncFileSystem):
             "GET",
             "b/{}/o/",
             bucket,
-            delimiter="/",
+            delimiter=delimiter,
             prefix=prefix,
             maxResults=max_results,
             json_out=True,
@@ -634,7 +634,7 @@ class GCSFileSystem(AsyncFileSystem):
                 "GET",
                 "b/{}/o/",
                 bucket,
-                delimiter="/",
+                delimiter=delimiter,
                 prefix=prefix,
                 maxResults=max_results,
                 pageToken=next_page_token,
@@ -972,6 +972,13 @@ class GCSFileSystem(AsyncFileSystem):
             out = set(re.findall(pattern, txt))
             raise OSError(out)

+    def find(self, path, details=False):
+        out, _ = sync(self.loop, self._do_list_objects, path, delimiter=None)
+        if details:
+            return out
+        else:
+            return [o['name'] for o in out]
+
     async def _rm(self, paths, batchsize):
         files = [p for p in paths if self.split_path(p)[1]]
         dirs = [p for p in paths if not self.split_path(p)[1]]
```

**Comment by martindurant** [comment]
@rjzamora - this might interest you, as listing files can often be a bottleneck when investigating a parquet dataset in the client. 

@alimanfoo , the diff above accelerated `gcs.find("hermes-misc/mock_append")` from 34s to 850ms.

**Comment by martindurant** [comment]
(I tried splitting the find for the above path into 12 concurrent prefixes, and get a ~30% improvement, but sometimes much worse, doubtless depending on whether the SSL pool has expired; I suspect on my home network I'm pretty bandwidth limited at this point)

**Comment by martindurant** [comment]
ping - I could use some input here. There are a number of approaches we could take, somewhere between the current behaviour (considering each directory separately, sequentially) to a find which completely sidesteps the cache, and inbetween the chance to set or use the cache when possible.

**Comment by martindurant** [comment]
ping @alimanfoo
