### ISSUE TITLE
Recursive operations always fail

### ISSUE THREAD

**Issue by pvanderlinden** [dask/gcsfs#307]
**What happened**:

- If you call `copy(path1, path2, recursive=True)` it will always fail on copying the root of your copy command (it tries to copy a "prefix" which will fail with FileNotFoundError
- If you call `rm(path, recursive=True)` it will fail with "backend error", which I think is caused by a concurrency which is to high, if I increase the batchsize, this will go away. I also noticed the cleanup of directories doesn't take into account the batchsize currently. The test directory contains about 1200 files, which will cause 60 requests concurrently.

**Environment**:

- Python version: 3.7
- gcsfs: 0.7.1
- fsspec: 0.8.4

**Comment by baxen** [comment]
I also had the same problem with copy (not yet with rm). The issue comes from https://github.com/intake/filesystem_spec/blob/master/fsspec/spec.py#L804-L806
where during a recursive copy it adds the base path (which is a "directory" and so does not exist in GCS) to the list of individual files to copy. 

Probably it makes sense for GCSFS to override `expand_path` from fsspec? But could also add an explicit directory filter to the list of files to copy (which might be a bit expensive). I'd be happy to make a PR to do this but want to confirm what approach to use here.

**Comment by baxen** [comment]
I have been using this workaround

```python
if recursive:
    sources = fs.expand_path(sources, recursive=True)
    sources = [s for s in sources if not fs.isdir(s)]
    return fs.copy(sources, dest, recursive=False)
```

**Comment by martindurant** [comment]
The above code will fail when a path is both a file and a directory, which happens commonly when people do mkdir using the CLI or web interface. This is the essential source of the problems. I think it may be better to do for copy what  already exists for `cat`, and choose to "ignore" failures; perhaps it could be improved to specify *which* exceptions should be ignored (not-found would be the only one here).

**Comment by baxen** [comment]
I can take a shot at this, I assume the change should go in fsspec by adding [a similar on_error option](https://github.com/intake/filesystem_spec/blob/master/fsspec/asyn.py#L224) to the top level copy? Can on_error default to omit with the specific not-found error?

**Comment by martindurant** [comment]
For copy, there would only be "raise" or "ignore" options - and it would make sense for recursive copy to ignore by default, if the exception is not-found.

**Comment by martindurant** [comment]
This is probably fixed with fsspec master
