### ISSUE TITLE
upload_chunk parameter mismatch

### ISSUE THREAD

**Issue by chrisroat** [dask/gcsfs#350]
When the `shortfall` branch is taken in `upload_chunk`, it looks as though the `location` parameter should be passed in. 

https://github.com/dask/gcsfs/blob/30f9a875c4ea4588339388c17203ac0474b8e840/gcsfs/core.py#L1544-L1556

**Comment by martindurant** [comment]
Please fix! In practice, I don't think that this code ever gets called any more, at least not for the blocksizes that people tend to use.

**Comment by chrisroat** [comment]
PR shortly with just the simple fix.  I'm not sure how to test it.

My pipeline recently hit this code path, which is how I came across it.

**Comment by martindurant** [comment]
OK, so my assertion that this doesn't happen was wrong :|

I don't know how to test it either. The testing infrastructure depends on recording real responses from the server, and we don't know how to make this condition happen.

Since the fix is obvious, please just make it. Just for once, adding typing would have helped.
